version: '3'
services:
  espial:
    image: '$HUB_REPO/$APPIMAGE'
    build:
      context: dist
      dockerfile: ../Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - '$APPDATA:/app/data'
    network_mode: host
    environment:
      - IP_FROM_HEADER=true
      - SQLITE_DATABASE=/app/data/espial.sqlite3
      # - SSL_ONLY=false
      # - DETAILED_LOGGING=false
      # - SHOULD_LOG_ALL=false
      # - ARCHIVE_SOCKS_PROXY_HOST=localhost 
      # - ARCHIVE_SOCKS_PROXY_PORT=8888
      # - SOURCE_CODE_URI=https://github.com/jonschoning/espial
      # - ALLOW_NON_HTTP_URL_SCHEMES=false
